checks:
  javascript: true
filter:
  excluded_paths:
    - test/*
    - node_modules/*
    - build/*
    - docs/*

build:
  cache:
    disabled: true

  environment:
    google_chrome:
      use_latest: true

    variables:
      CXX: g++-4.8


  dependencies:
    before:
      - export LATEST=$(nvm ls-remote | tail -1)
      - nvm install $LATEST
#      - nvm use $LATEST
      - sudo apt-get -y install software-properties-common python-software-properties
#      - sudo apt-cache policy gcc++
#      - sudo apt-cache policy g++
#      - sudo apt update -y
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt update -y
      - sudo apt-get install -y gcc-4.8
      - sudo apt-get install -y g++-4.8
      - sudo apt-get install -y libdbus-1-dev
      - sudo apt-get install -y libglib2.0-dev
      - sudo apt-get install -y dbus
      - npm install -g node-gyp
      - npm install -g grunt-cli
      - git config remote.origin.url
      - node -v

  tests:
    override:
      -
        command: 'grunt'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'

