language: node_js
node_js:
- node
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: slZGMTxHp6i8XKvDzTkWPP7u+kaXGJXIQrBuj/l1rkyRHu8EtdNmCmDrafT2ZjKQi0ePO5fFIi/LzToRB517bBXb4Bk0VT4IBlUADO7HfZ41Je6xxVAq1vf7/ah7dWXYbwPrkhtyC/BqnHRkewJexwWoMJqbdE9B1Vr8LLCy7QiDXmYApaXEBdGr5Mh3Vyl79Or6kzj8yh0T9MtprFALnVQotwGJEQXyPS6NQ2Fw31Vh1kNytB9bvTJxmjPQZ9Qk1vP6zXHtEDYDMd8W9FRizaphGSsGujVytDmoEbueLrVqoFUqVxFRATSTsGDKsYyGh9o5YX1pvQJkhl9swOXfdjqjyJYP7kRxRj2mvKQUoMyEkIHij3+Hi4O/dcbtzqfqTWI9fcOQWiVYQtCkrx3mmRT5RadSnINYV18UHjhuo1vjUhUKriMlLhIYzs3AXmBJKsSVdlTGFDmDzoOjNI0GwMiEc5chNxdXuihDaJ4/jaAc0Ix2GzhVH7Hnb2vRqzhtwD7ObhHlda9MniE3RDNjFp2WkTZLzNQ9QS4LK3lt41JHDUf3i8DWE/2UGTM0gDR7hrrpUNqPtCjzC19c7Rhkv90Dq+jC9NoIicTJBEiDN5uCH2tuwOKpuRgHFqa/sc8MQn/ghj1GiIDIcSlMi9do9BsHSm1kNEth4PWNjadPcrQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - dbus
    - dbus-x11
    - gcc-4.8
    - g++-4.8
    - libdbus-1-dev
    - libglib2.0-dev
before_script:
- npm install -g node-gyp
- npm install -g grunt-cli npm
