language: node_js
node_js:
- node
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: FhFgyp+z097U4oSXxb2+595426H5L9mSWrBoLYqd33nOGA4+Dvd4k12KijI8HFlRDGGtUvhraw/sv7f/vbWDD0tSuRSMm8094vMsxeJEgnIaBjWnV/vxU7Y2aCot8ZHVbyoUZd5cBuaQ2JGxalvjtOfX8NYGWWXT4plKI2usmp4dfKXh+jiiTZgNE/hGRQvl73Npke5aQCLudmGMQBuHSUacK+H7cSytYAI6YEfd6GE3Vg4xM7rmzF1N5SFzQvAyT60woa6ynCdmdhwhEQXzi88vvslM8w4a6+ZAN9PgzEs8ZPzgWRTjmTygqJl/w2fZpdN4k4YNkoBXKaZXBMvFJR7HLlnUTmxWslqnjePQWK4AGoLdIXmnmlmGDbCHFtp4WNGkbag8Rs+HUYTyL0B/BKZmLJXmN/j2evUxFPpJyQiEdqVhlcnMLYDU5MGwuCLke6k4MDrRjUqfwBA0dLmOOFQCrWyIK4uDCdutEUz6esw3KMfkB3SL8EFIl4opW33qITUkknXwXWkfj/06/ri7+cQqmRvvSJqfJ0FtsRjrDWEaD29N0/N27k7j/H1p+IhVomlWBCVYKXnqZgD8lAQzynZ3y+lunJOfzsVJ9o7nI8wUjCEpu9cIg2jleIH+tmH//EhBquEcOvZTavwmgORZuQYWCaBD+bA/FznZlLXQ4Ko=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - dbus
    - dbus-x11
    - gcc-4.8
    - g++-4.8
    - libdbus-1-dev
    - libglib2.0-dev
before_script:
- npm install -g node-gyp
- npm install -g grunt-cli npm
