language: node_js
sudo: required
node_js:
  - "7.8"
  - "node"
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_script:
  - npm install -g node-gyp
  - npm install grunt-cli -g
